GET http://localhost:8080/produtos

###

POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "controle",
    "descricao": "controle de tv",
    "preco": 9.99
}

###

POST http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "sofa cama",
    "descricao": "um sofa que vira cama",
    "preco": 9.99
}


###

PUT http://localhost:8080/produtos
Content-Type: application/json

{
    "nome": "sofa cama",
    "descricao": "um sofa que vira cama",
    "preco": 115
}


###

DELETE http://localhost:8080/produtos/1

###

